blank_issues_enabled: false
contact_links:
  - name: WebUI Community Support
    url: https://github.com/R-D-BioTech-Alaska/the-lonely-ai/discussions
    about: Please ask and answer questions here.
